### ISSUE TITLE
Abstract python sources from cpp-linter-action to cpp-linter repo

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#1]
_Originally posted by @shenxianpeng and @2bndy5 in https://github.com/cpp-linter/cpp-linter-action/pull/81 code review._

**Comment by shenxianpeng** [comment]
@2bndy5 You are the author of python sources, so I want to leave the first commit of migration to you.

**Comment by 2bndy5** [comment]
I have to finish testing PR events on https://github.com/cpp-linter/cpp-linter-action/pull/81 first. Once that's ready for the master branch, I'll migrate it over (the pypi tokens need to be regenerated also).

**Comment by 2bndy5** [comment]
To cause less confusion, I intend to start with the same version number that cpp-linter-action is on.

**Comment by shenxianpeng** [comment]
@2bndy5 assigning this issue to you just for your attention, I assume we are ready to abstract our python source from cpp-linter-action to here. You could start anytime when you are free.

**Comment by 2bndy5** [comment]
you want me to publish a release? or do you want to do it?

I'm guessing you want to use the tag 2.0.0, but there's no breaking changes from v1.4.5

We could keep this release to v1.5.0 and start releasing the cpp-linter-action repo with a v2.0.0 tag.

On a side note, I think having multiple tags for a commit messes with `setuptools_scm`. I think it would be more reliable to release using only a full semver tag (like v1.5.0). Then, after upload to PyPI is successful, we can add a short tag (like v1).

**Comment by 2bndy5** [comment]
I did a release for v1.4.6 to PyPI. I invited you as a collaborator for that cpp-linter project on PyPI.

**Comment by shenxianpeng** [comment]
> I think it would be more reliable to release using only a full semver tag (like v1.5.0).

It looks good me to use v1.5.0 instead of v2.0.0 for the next release

**Comment by 2bndy5** [comment]
I've had an idea about switching to git directly for getting a push event's diff (and list of changed files). Maybe such feature would warrant v1.5.0 tag also.

I'm just not sure how use git to list a diff for a PR. Determining the head and base commits in that context seems non-trivial.

**Comment by shenxianpeng** [comment]
Do you want to get push event diff using git instead GitHub API? it's a good idea if we can use git directly, and support other Non-GitHub SCM like Bitbucket and GitLab easily. This can be considered after v1.5.0 is released.
