### ISSUE TITLE
dead link created for diagnostic ID `clang-diagnostic-error`

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#105]
I saw the link https://clang.llvm.org/extra/clang-tidy/checks/clang/diagnostic-error.html can not reached, not sure if it's a wrong link or an issue with clang.llvm.org, just brought up it up for attention.

More details can be found here: `https://github.com/NikolaDucak/caps-log/pull/51#issuecomment-2099115811`

**Comment by 2bndy5** [comment]
looking at the [list of checks](https://clang.llvm.org/extra/clang-tidy/checks/list.html), there is no page for this diagnostic ID named `clang-diagnostic-error`. It may be a fallback ID or something...

It is not hard to prevent creating the dad link for this diagnostic ID. We only need to add a condition to https://github.com/cpp-linter/cpp-linter/blob/6ccb83495deebed5252b94018d027569b0684073/cpp_linter/clang_tools/clang_tidy.py#L82-L86

**Comment by 2bndy5** [comment]
In my pseudo-code I stored the diagnostic ID in a list because we will likely find more, especially if the clang docs' site navigation changes.

**Comment by 2bndy5** [comment]
From the [clang-tidy docs](https://clang.llvm.org/extra/clang-tidy/):

> Clang diagnostics have check names starting with `clang-diagnostic-<warning-option>`. Diagnostics which have a corresponding warning option, are named clang-diagnostic-<warning-option>, e.g. Clang warning controlled by `-Wliteral-conversion` will be reported with check name `clang-diagnostic-literal-conversion`.

So, this diagnostic is really just a way of referring to warnings/errors triggered by compiler flags.

> In my pseudo-code I stored the diagnostic ID in a list because we will likely find more, especially if the clang docs' site navigation changes.

Given the above discovery, we don't need a black list of diagnostic IDs that have no links. Instead we could just...
```py
    @property
    def diagnostic_link(self) -> str:
       """Creates a markdown link to the diagnostic documentation."""
       if self.diagnostic.startswith("clang-diagnostic-"):
           return self.diagnostic
       link = f"[{self.diagnostic}](https://clang.llvm.org/extra/clang-tidy/checks/"
       return link + "{}/{}.html)".format(*self.diagnostic.split("-", maxsplit=1))
```

**Comment by 2bndy5** [comment]
I also noticed that repo is using clang-tidy v19 (see [that repo's workflow config](https://github.com/NikolaDucak/caps-log/blob/d0fdeb9c9ac59b0015da639be962eed41bf1e739/.github/workflows/pr-check.yml#L112))

[According to our docs](https://cpp-linter.github.io/cpp-linter-action/inputs-outputs/#version), we only support up to v18. Should this be adjusted (again)?

**Comment by 2bndy5** [comment]
> The last version of [llvm is 18.1.5](https://github.com/llvm/llvm-project/releases), interesting.

Apparently, the PPA repository that cpp-linter-action uses on Linux also includes nightly builds. According to [llvm docs](https://apt.llvm.org/):

> Packages are available for amd64, i386 (Debian only), s390x and arm64 (aka aarch64). This for both the stable, qualification and development branches (currently 17, 18 and 19).

Reminder: most CI runners use AMD64 arch types (or at least the github [actions/runner-images]( www.github.com/actions/runner-images) use only AMD64).
