### ISSUE TITLE
Support other git hosting platforms (GitLab and Gitea)?

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#126]
The user in [this issue](https://github.com/cpp-linter/cpp-linter-action/issues/281) asked if we support platforms like GitLab or Gitea. 

The short answer is NO; we don’t currently support other platforms directly.

However, for GitLab and Gitea, you can use [cpp-linter/cpp-linter-hooks](https://github.com/cpp-linter/cpp-linter-hooks) with a `.pre-commit-config.yaml` file in your CI pipeline.

If you’d like us to add direct support for these platforms, please let us know—this helps us gauge the level of interest.

**Comment by 2bndy5** [comment]
I'd prefer a separate issue/thread for each requested git server; 1 separate issue for GitLab (see #101) and 1a separate issue for Gitea.
