### ISSUE TITLE
Support coding style Microsoft to file annotation

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#14]
Before clang-format 10 only supported following code style by default
LLVM, Google, Chromium, Mozilla, WebKit.

Since clang-format 11 supported GNU and Microsoft by default.
LLVM, GNU, Google, Chromium, Microsoft, Mozilla, WebKit.

How about supporting GNU and Microsoft to cpp-linter?

**Comment by 2bndy5** [comment]
Simple pass `GNU` or `Microsoft` to the `style` input. You could also use `file` as `style` input and set the `BasedOnStyle` field to any supported style in the clang-format file; this is what we do in the demo:
https://github.com/cpp-linter/cpp-linter/blob/d0149f6a8c52b330acf764cb2a546b4b833517f3/tests/demo/.clang-format#L3

The README might need to be updated to say:
> any style supported by the specified version of clang-format

**Comment by 2bndy5** [comment]
> Since clang-format 11 supported GNU and Microsoft by default.

It was my understanding that the LLVM style is the defacto default (when style is not specified.


----
> If the user does not want to have a .clang-format, but wants to pass "Microsoft" to their action, we do not support it at this moment.

Not sure what gave you that idea. Anything that clang-format support (depending on version used) is supported.
```
cpp-linter --style=GNU
```
is the same as 
```yml
- uses: cpp-linter/cpplinter-action@??
  with:
    style: GNU
```

**Comment by 2bndy5** [comment]
Keep reading that source and follow the logic
https://github.com/cpp-linter/cpp-linter/blob/d0149f6a8c52b330acf764cb2a546b4b833517f3/cpp_linter/clang_format_xml.py#L88-L95
`microsoft` is covered by the `style.title()`

That code is only used to output the file annotation about clang-format violation(s).

**Comment by 2bndy5** [comment]
oh, I see now we need to add microsoft to the condition
`style not in ("llvm", "google", "webkit", "mozilla", "gnu", "microsoft")`

**Comment by 2bndy5** [comment]
To be clear, we do support it, but the file annotation is incorrect in the case of using the `microsoft` style.
