### ISSUE TITLE
cpp-linter performing checkup on a new .c file failed

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#16]
I am trying to reproduce https://github.com/cpp-linter/cpp-linter/issues/18 in this PR https://github.com/shenxianpeng/test-repo/pull/6

But I have another problem. 

```bash
Performing checkup on p_enemy.c
  INFO:CPP Linter:Running "clang-tidy-14 --export-fixes=clang_tidy_output.yml -checks=boost-* ,bugprone-* ,performance-* ,readability-* ,portability-* ,modernize-* ,clang-analyzer-* ,cppcoreguidelines-* ,-cppcoreguidelines-avoid-magic-numbers ,-readability-magic-numbers --extra-arg= p_enemy.c"
  DEBUG:CPP Linter:Output from clang-tidy:
  
  Traceback (most recent call last):
    File "/home/runner/.local/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line [101](https://github.com/shenxianpeng/test-repo/actions/runs/3408873516/jobs/5669961676#step:3:106)2, in main
      capture_clang_tools_output(
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line 702, in capture_clang_tools_output
      run_clang_format(filename, file, version, style, lines_changed_only)
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line 600, in run_clang_format
      for line_range in file_obj["line_filter"][ranges]:
  KeyError: 'line_filter'
  Error: Process completed with exit code 1.
```

For more details see https://github.com/shenxianpeng/test-repo/actions/runs/3408873516/jobs/5669961676

**Comment by 2bndy5** [comment]
I think there's larger problem at work here. if you set `lines-changed-only: true` and the event included a diff in for the file, then there absolutely should be a key named `line_filter` in the dict. The code that creates the key is in `filter_out_non_source_files()`:
https://github.com/cpp-linter/cpp-linter/blob/a23e14ddcfaef83da0f4aca740dbfd547163e207/cpp_linter/run.py#L388-L408

All this to say: Why wasn't there a diff included in the event for that file?

**Comment by 2bndy5** [comment]
This wouldn't be problem if I can get the solution for #4 working in the CI runner.

I also thought about switching to requesting the diff format for REST API call that gets the changed files of an event.

**Comment by 2bndy5** [comment]
I think the real culprit here is that GitHub didn't bother with a diff because the `status` of the file was `"added"`. It would be nice if they mentioned this kind of detail in their REST API docs.
https://api.github.com/repos/shenxianpeng/test-repo/pulls/6/files

**Comment by 2bndy5** [comment]
That just means that clang-format found problems with the listed lines.

**Comment by 2bndy5** [comment]
> it should also display other messages "Code does not conform to {style_guide} style guidelines.", but it's too long.

Yes, that's a compromise I made. You cannot make more than 50 annotations in a single workflow run. I think the limit for message content is something larger (can't remember the exact number of bytes). So instead of creating an annotation for every line that didn't pass the checks, I just put the entire list in 1 annotation at the beginning of the file.

**Comment by 2bndy5** [comment]
I thought the title, "Run clang-format on p_enemy.c: p_enemy.c#L1", would have implied that code does not conform to clang-format settings.

**Comment by 2bndy5** [comment]
It might be easier to use an ellipses when the number of lines is too long to fit in the annotation. Maybe something like
>File p_enemy.c (lines 15 ... 2423) Code does not conform to {style_guide} style guidelines
