### ISSUE TITLE
Failed with "IndexError: list index out of range"

### ISSUE THREAD

**Issue by turol** [cpp-linter/cpp-linter#22]
https://github.com/chocolate-doom/chocolate-doom/pull/1539
https://github.com/chocolate-doom/chocolate-doom/actions/runs/3488670039/jobs/5837974167

Failed with
```
  INFO:CPP Linter:Running "clang-tidy-14 --export-fixes=clang_tidy_output.yml -checks=boost-* ,bugprone-* ,performance-* ,readability-* ,portability-* ,modernize-* ,clang-analyzer-* ,cppcoreguidelines-* ,-cppcoreguidelines-avoid-magic-numbers ,-readability-magic-numbers --line-filter=[{"name": "src/heretic/p_pspr.c", "lines": [[1824, 1825]]}] --extra-arg= src/heretic/p_pspr.c"
  DEBUG:CPP Linter:Output from clang-tidy:
  
  Traceback (most recent call last):
    File "/home/runner/.local/bin/cpp-linter", line 8, in <module>
      sys.exit(main())
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line 1029, in main
      capture_clang_tools_output(
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line 716, in capture_clang_tools_output
      run_clang_format(filename, file, version, style, lines_changed_only)
    File "/home/runner/.local/lib/python3.8/site-packages/cpp_linter/run.py", line 615, in run_clang_format
      cmds.append(f"--lines={ranges[0]}:{ranges[1]}")
  IndexError: list index out of range
  Error: Process completed with exit code 1.
```

Another PR in the same repo around the same time succeeded
https://github.com/chocolate-doom/chocolate-doom/pull/1550
https://github.com/chocolate-doom/chocolate-doom/actions/runs/3482166515/jobs/5837919331

Maybe it has something to do with passing a range of just one line?

**Comment by 2bndy5** [comment]
This is actually my mistake. In #21, I switched to using a function that returns a list of line numbers. But clang-format/tidy CLI expect beginning and ending line numbers of a range... This is an easy fix.

#23 will resolve this

**Comment by 2bndy5** [comment]
It seems like sheer luck that the unit tests passed with this regression present. All files used by the unit test must have an even number of changed lines.
