### ISSUE TITLE
Reformat action thread comments

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#24]
The [thread comments](https://github.com/cpp-linter/cpp-linter-action#thread-comment) not looks fancy than other projects:

- codecov https://github.com/cpp-linter/cpp-linter/pull/21#issuecomment-1312488830
- sonarcloud https://github.com/cpp-linter/cpp-linter/pull/21#issuecomment-1312673279
- dependabot https://github.com/shenxianpeng/blog/pull/59#issue-1411851725

Maybe we could reformat thread comments, I draft a new one (WIP), and I will continue to update if there is a new idea.

# Cpp-Linter Report ⚠️

Some files didn't pass the configured checks.

<details><summary>Check the details</summary>

<strong>The following files need to be formatted (report from [clang-format](https://clang.llvm.org/docs/ClangFormat.html)) </strong>

- demo.hpp
- demo.cpp

<strong>The following files have static analysis errors (report from [clang-tidy](https://clang.llvm.org/extra/clang-tidy/))</strong>

<details>
<summary>demo.hpp</summary>
<br>
<strong>demo.hpp:10:11:</strong> warning: [modernize-use-trailing-return-type]

> use a trailing return type for this function
<p>

```.hpp
    void *not_usefull(char *str){
    ~~~~~~^
    auto                         -> void *
```
</p>

<strong>demo.hpp:12:16:</strong> warning: [modernize-use-nullptr]

> use nullptr
</summary><p>

```.hpp
        return 0;
               ^
               nullptr
```
</p>
</details>

<details><summary>demo.cpp</summary><br>

<strong>demo.cpp:5:5:</strong> warning: [modernize-use-trailing-return-type]

> use a trailing return type for this function

```.cpp
int main()
~~~ ^
auto       -> int
```

<strong>demo.cpp:7:13:</strong> warning: [readability-braces-around-statements]

> statement should be inside braces

```.cpp
    for (;;)
            ^
             {
```

<strong>demo.cpp:11:5:</strong> warning: [cppcoreguidelines-pro-type-vararg]

> do not call c-style vararg functions

```.cpp
    printf("Hello world!\n");
    ^
```
</details>

</details>

Have any feedback or feature suggestions? [Share it here.](https://github.com/cpp-linter/cpp-linter/issues) 

---

# Cpp-Linter Report ✔️

No problems need attention.

Have any feedback or feature suggestions? [Share it here.](https://github.com/cpp-linter/cpp-linter/issues)

**Comment by 2bndy5** [comment]
I have no objections to this.

**Comment by 2bndy5** [comment]
If this is to be shown after successful runs, then I think it would be good to be more concise.



# Cpp-Linter Report ✔️

No problems need attention.

Have any feedback or feature suggestions? [Share it here.](https://github.com/cpp-linter/cpp-linter/issues)

**Comment by 2bndy5** [comment]
Instead of showing the errors, we could show a simple table that summarizes the results.

| file | clang-tidy | clang-format |
|----|:----------:|:------------:|
| demo/demo.cpp | 🔴  | 🟢  |

---
[complete emoji choices](https://github-emoji-picker.vercel.app/)

**Comment by 2bndy5** [comment]
Or we could hide the summary table in a details tag

# Cpp-Linter Report ⚠️
Some files didn't pass the configured checks.

<details><summary>sumary table</summary>

| file | clang-tidy | clang-format |
|:----|:----------:|:------------:|
| demo/demo.cpp | 🔴  | 🟢  |

</details>

**Comment by 2bndy5** [comment]
> if users don't enable both clang-format and clang-tidy how to show it in the table?

I was thinking we could use 🚫 or ⛔ instead of 🔴/🟢. FYI, the longer the emoji code, the less data we can fit in the comment.

> maybe a separate display is more suitable.

What did you have in mind?

**Comment by 2bndy5** [comment]
You know me: anything is possible. I just need a concrete decision before coding the solution.

So, if `tidy-checks` is `'-*'` or style is `''`, then we go with a list. Otherwise we show a table. Yes?

**Comment by 2bndy5** [comment]
I only suggested the table because
1. it will reduce the occupied screen real estate when user expands the details.
2. not showing the info about the reported errors will allow us to fit more summary info in the comment. Remember that the comment's size is limited by the REST API max payload size, so a thread comment about a very large diff (with lots of errors/warnings to report) will be truncated by the REST API's max payload size. There isn't a way around this max limit. I know other actions hide the ending portion of their potentially large comments in a `<details>` tag just in case the payload is truncated.

**Comment by 2bndy5** [comment]
One thing I noticed about all the example comments you linked to in the OP was that they all show an overview instead of detailed info. So, I thought that was partly what you wanted to mimic.

**Comment by 2bndy5** [comment]
LGTM

**Comment by 2bndy5** [comment]
I just found an additional feature in github actions: The [GITHUB_STEP_SUMMARY](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary) will post a markdown content at the bottom of the run's summary. Its not exactly like `thread-comments` (the markdown payload is the same), but at least we wouldn't have to worry about duplicate bot comments.

Someone even uses the feature in an existing action that produces a unit test summary comment in the workflow's run summary. For example, [this run summary](https://github.com/zephyrproject-rtos/zephyr-testing/actions/runs/3473063608/attempts/1#summary-9507956909) shows the custom summary that we could create.

**Comment by 2bndy5** [comment]
It wouldn't be too hard to implement, we just need to add an input option to turn it on/off and add
```py
with open(os.environ["GITHUB_STEP_SUMMARY"], "a") as summary:
    summary.write(Globals.OUTPUT)
```

**Comment by 2bndy5** [comment]
Yep! We don't have to check for duplicate comments and all that entails either.

**Comment by 2bndy5** [comment]
sorry this still on my todo list, but I've been busy.

**Comment by 2bndy5** [comment]
> **Note**
I recently noticed that github added support for admonitions (AKA "callouts"). See [example here](https://github.com/orgs/community/discussions/16925).

> **Warning**
But it looks like only "note" and "warning" are supported (in English only). I also don't like how this looks in dark mode. Block quotes' dimmed text was a bad choice.
