### ISSUE TITLE
Ignore files not listed in the database

### ISSUE THREAD

**Issue by Tich-fr** [cpp-linter/cpp-linter#28]
Because of dependencies I cannot create a valid compilation database for all the cpp files of my repo. I'd expect that files that does not appear in the compilation database shouldn't  be processed, because their warnings will be wrong most of the time anyway.

This is more of a quality-of-life feature request, because one can use the `ignore` parameter.

@2bndy5 if you think this makes sense I may take a look at this when I have some time

**Comment by 2bndy5** [comment]
> This is more of a quality-of-life feature request

Seems more like a request for extra intuition. I'm all for it as long as it doesn't break anything.

**Comment by BurningEnlightenment** [comment]
IIRC the compilation database doesn't list any header files, but they are linted by this action. Not linting header files also doesn't compose well with the only-changed-files option. So it would be a breaking change.

**Comment by 2bndy5** [comment]
I don't think it would be a major breaking change since the change is specific to a new feature. To keep backward compatibility, we can just try to make the default value for the new option behave like it did before the new option.

**Comment by Tich-fr** [comment]
That's right, but the database not listing headers is something I had not taken into account .. not sure how I'll deal with that in the implementation

**Comment by 2bndy5** [comment]
You could feed [`pathlib.Path.glob()`](https://docs.python.org/3/library/pathlib.html#pathlib.Path.glob) patterns to search for any relevant src files.

I must say that parsing a compilation database could be a bigger undertaking than you think; they have different versions and formats.
