### ISSUE TITLE
change output var into an exit code that can be silenced

### ISSUE THREAD

**Issue by 2bndy5** [cpp-linter/cpp-linter#5]
Well, I got the output var working as an exit code [in a composite action workflow]... See [this github doc for reference](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context)

I replaced  the action's output variable with a new input option called `quiet-fail`.
- If `quiet-fail` is false, then the action will return an unsuccessful exit code (`1`) but only if checks failed.
- If `quiet-fail` is true, then the action will return a successful exit code (`0`) despite whether or not checks failed.

I intend to make this new input into a CLI option for cpp-linter pkg. The default value will be set to true, so it shouldn't break any workflows that are currently ignoring the output variable.

_Originally posted by @2bndy5 in https://github.com/cpp-linter/cpp-linter-action/issues/83#issuecomment-1225508547_

**Comment by shenxianpeng** [comment]
> I intend to make this new input into a CLI option for cpp-linter pkg. The default value will be set to true, so it shouldn't break any workflows that are currently ignoring the output variable.

Do you mean `quiet-fail` will be set to true, right? and it will not break the workflow that uses the output variable named `checks-failed`? but it was removed from the commit [2c0996](https://github.com/cpp-linter/cpp-linter-action/pull/83/commits/2c09969c6d2f42e4bad4608948cb04e07b9a6ab5), so it still will not break?

From the [github doc](https://docs.github.com/en/actions/learn-github-actions/contexts#steps-context) description, the property  `steps.<step_id>.outcome` looks better than `steps.<step_id>.outputs.<output_name>`, but I'm afriad I still don't get the point of this change.

**Comment by 2bndy5** [comment]
Test runs indicated that the output variable was not propagated to the calling workflow. The output variable can be used in the composite steps, but it doesn't seem to be passed to the runner of the composite action.

**Comment by 2bndy5** [comment]
closing this as it be a breaking change, and we don't seem to need this since my original diagnosis.
