### ISSUE TITLE
Adding an option to pass `--extra-arg` to clang-tidy

### ISSUE THREAD

**Issue by hillmich** [cpp-linter/cpp-linter#7]
For a header-only library I'm maintaining the clang-tidy checks fail with warnings about c++17 features being used. This is most likely cause by clang-tidy assuming C++14 for the header files (since it's the default). Running `clang-tidy` manually with ` --extra-arg="-std=c++17"` fixes (most) problems. You can the library at cda-tum/dd_package#104

Could you add a parameter to `cpp-linter` to pass along extra arguments to `clang-tidy`?

**Comment by 2bndy5** [comment]
sounds reasonable. Does your generated database not have the `-std` arg in it?

**Comment by hillmich** [comment]
The generated database has the `-std` flag, but it seems clang-tidy doesn't pick it up automatically for the headers.

Just for completeness, the database for the source files looks like this

```
cat build/compile_commands.json
[
{
  "directory": "/home/runner/work/dd_package/dd_package/build/test",
  "command": "/usr/bin/clang++-14  -I/home/runner/work/dd_package/dd_package/include -O3 -DNDEBUG -Wall -Wextra -pedantic -fno-math-errno -ffinite-math-only -fno-trapping-math -mtune=native -march=native -std=c++17 -o CMakeFiles/DDPackage_example.dir/main.cpp.o -c /home/runner/work/dd_package/dd_package/test/main.cpp",
  "file": "/home/runner/work/dd_package/dd_package/test/main.cpp"
}, ...
```
