### ISSUE TITLE
what's happened to RST? 

### ISSUE THREAD

**Issue by shenxianpeng** [cpp-linter/cpp-linter#95]
😢 

<img width="375" alt="image" src="https://github.com/cpp-linter/cpp-linter/assets/3353385/7ac1ff2e-848d-4b60-9d93-4176830e8677">

**Comment by 2bndy5** [comment]
I noticed this too. It might just be some update to the Github's RST renderer.

Alternatively, we could organize the badges in a table. Or use RST substitutions to inline badges. I'll look into it.
